services:
    app:
        build:
            context: .
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - "8000:8000"
            - "9003:9003"
        networks:
            - laravel
        command: supervisord -c /etc/supervisor/conf.d/supervisord.conf

    db:
        image: mysql:8.0
        container_name: mysql_db
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - ./db_data:/var/lib/mysql
        networks:
            - laravel

networks:
    laravel:
