services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        depends_on:
            - redis
            - db
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        ports:
            - "8000:8000" # Porta do Laravel (HTTP)
            - "6001:6001" # Porta do Laravel Echo Server (WebSockets)
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=laravel
            - DB_PASSWORD=secret
        networks:
            - laravel
        command: supervisord -c /etc/supervisor/conf.d/supervisord.conf

    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: mysql_db
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - ./db_data:/var/lib/mysql
        networks:
            - laravel

volumes:
    redis-data:

networks:
    laravel:
